### ISSUE TITLE
Style page to match Pokemon Theme

### ISSUE THREAD

**Issue by Ahoward21** [Ahoward21/pokemon-search#3]
Use a styling platform such as bootstrap to style the page to match a pokemon theme

**Comment by nickperel** [comment]
Going to create a search input that looks like a Poke ball, using red and white colors and a ball shape. Also, the actual search button itself that we click will be the very center of the poke ball in a circular shape.

**Comment by nickperel** [comment]
Search input now looks like a pokeball and the elements on the screen were manipulated to match pokemon theme and colors, issue is resolved
